Implement Newsweek.com clone.
pointerish/NewsweekCloneMicroverse pull request #1
Opened 2020-10-19 17:42 UTC by pointerish

This clone was done using Bootstrap for layout and out of the box styling. Sass was used to customize some sections.

2020-10-22 19:33 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [x]   Please make your PR descriptive. Please add more details to it. Please refer to [link 1 ](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request)to learn how to create PR and Edit it and [link 2](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/) to how to make it descriptive.  

- [x] [Optioanl] Please add **bootstrap-4.5.3-dist folder**, **favicon.png**, **newsweek-screenshot.png**, and **style.css** in a sible folder so that your repsiotory looks clean. 

- [x] In your CSS Too many font-size declarations (13), abstraction needed.

- [x] In Bootstrap projects make sure to less use the styles.css file for styles that could be done using Bootstrap classes since that's the main goal of the exercise. Things like font-weight, flex justifications, display, etc could be implemented completely with Bootstrap classes. Please refer to the main page of bootstrap to learn more about bootstrap.

- [ ] [Optioanl] Don't use IDs in selectors.

# Large Screen

- [ ]  There is white space around the page so your page is centered. I cannot see anything aligned correctly. Please work on it. Everything on your page is compressed.

- [x] Please work on the navbar. Your navbar doesn't look alike the original one. 

**Clone**

![chrome-capture (8)](https://user-images.githubusercontent.com/58504655/96917082-da618580-14c1-11eb-95bf-4e9a736d479d.jpg)

- [ ] Please add more items in the More Stories section. 

**clone**

![chrome-capture (9)](https://user-images.githubusercontent.com/58504655/96917441-58259100-14c2-11eb-9b86-2d2418d245a5.jpg)

- [x] EDITOR'S PICK section should have a total of 8 items 4 per row but you have 3 per row. 

- [x] You have used the US for all the sections. Please give them a proper name as present on the original page and remove extra spacing under items. 

- [ ] Please use proper images

**clone**

![chrome-capture (10)](https://user-images.githubusercontent.com/58504655/96917923-ed288a00-14c2-11eb-9f3b-2c26569e163a.jpg)

- [x] Subscribe and Newsletter section should have space between them and there should some space between email input field and signup button 

**Clone**

![chrome-capture (10)](https://user-images.githubusercontent.com/58504655/96918111-3d9fe780-14c3-11eb-85b6-e151bbbf1f28.jpg)

- [x] Subscribe section should have two images overlapping each other. 

- [x] text **@2020 NEWSWEEK** should be properly aligned. 


# Medium Size

- [x] On tablet mode, the subscribe button and hamburger have more space between them. Please resolve this. 

**Clone**

![chrome-capture (11)](https://user-images.githubusercontent.com/58504655/96919736-a4260500-14c5-11eb-9188-10e66f8b4dbc.jpg)

- [x] On your clone, everything is stretchy. Please work on it and make it like the original one. 

- [x] On your clone in IN THE MAGAZINE section only one item is present per row but on the original page, it looks exactly like the present on the large screen. 

- [ ] On the medium screen, the navbar should be sticky.

- [ ] Please have a look at the suggestions below. 
![chrome-capture (12)](https://user-images.githubusercontent.com/58504655/96920225-52ca4580-14c6-11eb-88d6-de13e02937d1.jpg)

# small screen

- [ ] On the small screen, the navbar should be sticky.


- [ ] On the small screen navbar should be small.

- [ ] On the small screen images in the subscribe section should be small and text should overlap the images. 

- [ ] On the small screen in the Newsletter section image should be small and text should be bold. 

- [ ] On the small screen, Footer icons disappear from the screen. 

**clone**

![chrome-capture (13)](https://user-images.githubusercontent.com/58504655/96920740-fb78a500-14c6-11eb-8d64-1d7250653c6b.jpg)


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-23 17:58 UTC, ebeagusamuel requested changes
### Changes Required :recycle: 
Hi there. Great work you've done on the project and in implementing some of the previous TSE recommendations :+1: 
However, there are still some issues raised by the previous TSE that still needs to be addressed :writing_hand: 

### On Large Screen
- [ ] Just like the previous TSE pointed out, the are some white space around your page that makes it not to take up the whole screen size just like the original website does. You can fix this by assigning a width of 100% to the body element. And also your nav doesn't seem to behave like that of the original website. Here is what your clone looks like.
![Screenshot from 2020-10-23 18-08-06](https://user-images.githubusercontent.com/57847212/97033456-4ba14700-155b-11eb-91f3-2336d87c32ca.png)

- [ ] Your more story section still lacks items. You currently have 2 items in your more story section as opposed to what the original website has. Please do add more content to that section. 
![Screenshot from 2020-10-23 18-23-41](https://user-images.githubusercontent.com/57847212/97034499-ef3f2700-155c-11eb-916a-81c778c024bb.png)
- [ ] The part captured in the screenshot below of your clone does not appear to be on the original website. Please remove it.
- clone
![Screenshot from 2020-10-23 18-30-07](https://user-images.githubusercontent.com/57847212/97035174-d84d0480-155d-11eb-853e-febb282cf496.png)
- Original
![Screenshot from 2020-10-23 18-31-45](https://user-images.githubusercontent.com/57847212/97035293-092d3980-155e-11eb-8b63-36d8d3ba7cbb.png)
- [ ] The subscribe section has some alignment issues. I think most of the problem is because your page is compressed and doesn't take the sie of the whole page. Try to fix that.
- clone 
![Screenshot from 2020-10-23 18-38-56](https://user-images.githubusercontent.com/57847212/97035972-097a0480-155f-11eb-8119-ed310b52d2a6.png)
- Original
![Screenshot from 2020-10-23 18-39-29](https://user-images.githubusercontent.com/57847212/97036031-20b8f200-155f-11eb-90d0-ff71be4f18bb.png)
### On Medium Screen
- [ ] There is too much space between the subscribe button and the hamburger.
- clone
![Screenshot from 2020-10-23 18-44-33](https://user-images.githubusercontent.com/57847212/97036501-d5531380-155f-11eb-94cb-d6bb74e337e8.png)
- original
![Screenshot from 2020-10-23 18-45-20](https://user-images.githubusercontent.com/57847212/97036574-eef45b00-155f-11eb-9bd2-740c1bac1a54.png)
- [ ] On the subscribe section and the newsletter section of your clone, the subscribe button and the email form do not look like the original one. Please correct this.
- clone 
![Screenshot from 2020-10-23 18-50-32](https://user-images.githubusercontent.com/57847212/97037053-a8ebc700-1560-11eb-83f1-83d7246f54b1.png)
![Screenshot from 2020-10-23 18-51-24](https://user-images.githubusercontent.com/57847212/97037133-c7ea5900-1560-11eb-902f-59774b4331b1.png)
- Original
![Screenshot from 2020-10-23 18-52-01](https://user-images.githubusercontent.com/57847212/97037208-dd5f8300-1560-11eb-9cc0-9363e9eaa72c.png)
![Screenshot from 2020-10-23 18-52-35](https://user-images.githubusercontent.com/57847212/97037259-f2d4ad00-1560-11eb-91b3-658e8a9c14ee.png)

Please do apply these changes and request another review when done. 
Happy coding :smile: 

Ebeagu Samuel
Slack(@ebeagusamuel)

2020-10-23 21:17 UTC, mimipeshy commented
**CHANGES REQUESTED!**

Hi @pointerish, I am very impressed by all the changes you have done as pointed out by the previous TSE's. I liked the fact that you implemented bootstrap classes to achieve such styling, kudos for that :clap: However, you are almost so close to completing this project.  

- [ ] Fix the trending menu bar, they should all be in one line. Check reference below :arrow_down: 
clone 
![clone](https://user-images.githubusercontent.com/33067256/97054389-6096ce00-158d-11eb-9ce4-f87fe9a6c9ec.png)
original 
![original](https://user-images.githubusercontent.com/33067256/97054397-62f92800-158d-11eb-93f7-2176413efd08.png)

- [ ] Also on the trending menu bar try and remove the shadow above it to make it look like the original menu. The shadow is declared on the header class.

Don't give up you are almost there :smiley: 
Please do apply these changes and request another review when done.
Happy coding :computer_mouse: 

Peris Ndanu
Slack(@perisndanul)

2020-10-23 22:58 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @pointerish  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far. I can see that you have tried enough to implement all of the required changes in the previous code reviews, keep it up :muscle: :muscle: :muscle: 

## :warning: However we need to make few changes to mark this project approved, don't feel disppointed or giving up, this is a learning process, and your progress is really great. Ypur project lacks only minor final touches to get approved :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# Required Changes :red_circle: 
- [ ] Since the first review, the TSE suggested you to reduce the extra-space which is on the each side of your clone (I notice that this extra-space appears when the screen size becomes greater that 1999px, whereas the original page doesn't behave like that)
Your clone : 
![Screenshot from 2020-10-24 00-01-04](https://user-images.githubusercontent.com/56886064/97059425-aef99c00-1590-11eb-92a1-13a1037772bb.png)

Original : 
![Screenshot from 2020-10-24 00-02-10](https://user-images.githubusercontent.com/56886064/97059476-d0f31e80-1590-11eb-984e-3cd057bc6031.png)

- [ ] Your clone get messed on medium screens width
Your clone on tablets which are in range of  (573 px - 481 px): 
![Screenshot from 2020-10-24 00-38-45](https://user-images.githubusercontent.com/56886064/97059688-668eae00-1591-11eb-86b3-9746d3339e5c.png)
Original page on tablets of that range  (573 px - 481 px):
![Screenshot from 2020-10-24 00-41-12](https://user-images.githubusercontent.com/56886064/97059760-a3f33b80-1591-11eb-8bfc-8b4b216e2e42.png)

- [ ] Use the same colors on `subscribe button` and `free signup button`
Your clone: 
![Screenshot from 2020-10-24 00-45-02](https://user-images.githubusercontent.com/56886064/97059984-56c39980-1592-11eb-9565-627edf396afb.png)
Original page:
![Screenshot from 2020-10-24 00-45-30](https://user-images.githubusercontent.com/56886064/97060466-b2425700-1593-11eb-84a1-3de0562c307c.png)
===> Even though all are reds, but those reds are different, please use the red which is on the original page

- [ ] Read the comments I wrote in your codes and resolve them.

# Optional changes :large_blue_circle: 
- [ ] Your commit messages should be in imperative mode, something like modify to solve linters reviews in css code instead of modified to solve linters reviews in css code, refer [to this article for mor details](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)
- [ ] Don't link scripts in head, all of scripts should be put on the bottom of the body of your html content


If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-10-23 22:58 UTC, descholar-ceo commented on .gitignore
> +.hintrc
Remove this `.hintrc` from .gitignore file, it is need with github actions, when you push your code on github. So it's beneficial to have it in your repo. Don't let it out.

2020-10-23 22:58 UTC, descholar-ceo commented on index.html
> +  <link rel="stylesheet" href="assets/bootstrap-4.5.3-dist/css/bootstrap.min.css">
I guess this was by mistake, that you linked one file twice, you can just delete one link

2020-10-23 22:58 UTC, descholar-ceo commented on index.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/plugins/CSSPlugin.min.js"></script>
Link script links at the bottom of the body of your html, don't link them here in head tag

2020-10-24 02:57 UTC, ebeagusamuel approved these changes
## Project Approved :man_dancing: 
Congratulations @pointerish 
#### Well done for persisting and implementing all the changes the previous TSEs pointed out. Your project now looks great :champagne: 
Please you can go ahead and merge into the main branch.

#### Goodluck with your other projects :smiley: 

Ebeagusamuel
slack(@ebeagusamuel)

2020-10-24 03:04 UTC, merged